apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-api
spec:
  releaseName: demo-api
  values:
      deployment:
        image: 
          repository: "colinmac.azurecr.io/samples/simplegreeting"
          pullPolicy: Always
          tag: latest
        env:
          - name: GREETING
            value: "Hello from Production!"
      ingress:
        className: nginx-private
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
          nginx.ingress.kubernetes.io/use-regex: "true"
        hosts:
        - host: "prod.colinmac.dev"
          paths:
            - path: /demo(/|$)(.*)
              pathType: Prefix
              servicePort: 80
        tls:
        - hosts:
          - prod.colinmac.dev
      osm:
        enabled: true
        proxySslSecret: "core-platform/osm-private-nginx-client-cert"
        ingressNamespace: core-platform
        ingressService: ingress-nginx-private-controller
        ingressServiceAccount: ingress-nginx-private