apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-api
spec:
  serviceAccountName: shared-services-developers
  releaseName: demo-api
  chart:
    spec:
      chart: ./charts/azure-basic-api
      # version: "" latest
      sourceRef:
        kind: GitRepository
        name: shared-services-developers
  interval: 5m
