apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-api
spec:
  serviceAccountName: shared-services-developers
  releaseName: demo-api
  chart:
    spec:
      chart: ./charts/azure-basic-api
      # version: "" latest
      sourceRef:
        kind: GitRepository
        name: shared-services-developers
  interval: 5m
  values:
      deployment:
        image: 
          repository: "colinmac.azurecr.io/samples/simplegreeting"
          pullPolicy: Always
          tag: latest
        env:
          - name: GREETING
            value: "Hello!"
        containerPorts:
          - name: https
            containerPort: 443
            hostPort: 443
            protocol: TCP
          - name: http
            containerPort: 80
            hostPort: 80
            protocol: TCP
      ingress:
        className: nginx-ingress-private
        # annotations:
        #   nginx.ingress.kubernetes.io/rewrite-target: /$1
        hosts:
        - host: "prod.colinmac.local"
          paths:
            - path: /
              pathType: Prefix
              servicePort: 80
      service:
        type: ClusterIP
        ports:
          - port: 80
            targetPort: http
            protocol: TCP
            name: http
          - port: 443
            targetPort: https
            protocol: TCP
            name: https